<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php
        $this->layout()->menu = $this->action('menu', 'user', 'default');
        ?>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-language" content="en" />
        <meta name="robots" content="noodp,noydir" />
        <title>Nidorx</title>
    </head>
    <body>
        <?php echo $this->layout()->menu; ?>
        <div>
            <?php echo $this->layout()->content; ?>
        </div>
    </body>
</html>

